name: e211
channels:
  - eoas_ubc
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - click
  - jupyter
  - git
  - jupytext
  - pillow
  - pip
  - scipy
  - matplotlib
# conda-lock -f environment.yml -p linux-64
